### PR TITLE
Fix for Dir Watcher for OSX (issue #192)

### PR DESCRIPTION
**Pull request by p4tin**
I believe this might fix it but I cannot test without knowing how to create the new iris binary for OSX.

### CODE REVIEW

**Comment by kataras** [comment]
go to your $GOPATH/src/github.com/iris/iris run `go install`and test it, I can't approve that yet

**Comment by p4tin** [comment]
It Works on my Mac!!!

**Comment by kataras** [comment]
So the 'fix' is to add RENAME event also? , on what editors do you test it?

**Comment by p4tin** [comment]
Yes - I tested with atom and WebStrorm,  seems some editors on mac create temporary files to save the changes then they do a rename.

**Comment by p4tin** [comment]
Was a slip of the mouse - I re-starred and Watched :)

**Comment by kataras** [comment]
The iris run is not part of the main framework, the new [library](https://github.com/kataras/rizla) doesn't checks for event now, all events are passed (write,rename,remove,create) this is the most correct because we must reload on every change, even a new go file. @p4tin You're welcome to contribute there if you have time!!

**Pull request closed without merging**
