### PR TITLE
#1949 fix "DisableBodyConsumptionOnUnmarshal" is ignored in "ReadJSON…

### PR DESCRIPTION
**Pull request by yjz2222**
#1949 fix "DisableBodyConsumptionOnUnmarshal" is ignored in "ReadJSON" and "ReadJSONStream"

### CODE REVIEW

**Comment by kataras** [comment]
Hello @yjz2222, this code is copied from a previous commit of mine. There is another workaround, changing the ReadJSON before serve-time. If ReadJSON with disable unmaeshal option does not work for you, open a issue.

**Comment by yjz2222** [comment]
> 

Thanks for your reply, I tried to use my own implementation of Unmarshaler and BodyDecoderWithContext interfaces to deserialize json, this is fine, because the source code uses ctx.GetBody() when calling these interfaces, but the same ignored DisableBodyConsumptionOnUnmarshal property, so I submit the change is meaningless?

**Comment by kataras** [comment]
Hello @yjz2222,

Of course, you are welcomed! It's ok but there is a better way: The `ctx.ReadJSON` was modified in the last revisions, so it can be fully customized to the developer's needs. The `ctx.ReadJSON` is calling the `context.ReadJSON` package-level variable/function, which can be modified, for example when `DisableBodyConsumptionOnUnmarshal` is true, we know the configuration value **before serve-time**, so we can modify the `context.ReadJSON` instead of adding extra logic inside it to make the request body persistence when decoding it.

**Comment by yjz2222** [comment]
okay ,i c, thanks again

**Comment by kataras** [comment]
@yjz2222 the thing is that there is a functionality for "body recording" via middleware, in serve-time. So we can't modify the ReadJSON at startup, the correct solution which I'll push right now, matches yours and the previous implementation of ctx.ReadJSON, is: 


```go
	var body io.Reader = ctx.request.Body

	if ctx.IsRecordingBody() {
		data, err := io.ReadAll(body)
		if err != nil {
			return err
		}
		setBody(ctx.request, data)
		body = bytes.NewReader(data)
	}

	decoder := json.NewDecoder(body)
	// ...
```

**Comment by yjz2222** [comment]
yes,this is much easier, and I think it should have been, otherwise I would have needed to manually adjust the ReadJSON function before creating a new iris instance, something like this：
```
app := iris.Default().Configure(iris.WithoutBodyConsumptionOnUnmarshal)
	context.ReadJSON = func(ctx *context.Context, outPtr interface{}, opts ...context.JSONReader) error {
		if ctx.IsRecordingBody(){
			......
		}
		.....
	}
```

**Pull request closed without merging**
