### PR TITLE
update host.ProxyHandler to compatiable with different hosts in target url and request host

### PR DESCRIPTION
**Pull request by tuhao1020**
#1702

### CODE REVIEW

**Comment by kataras** [comment]
Hello @tuhao1020, sorry for the delay response.

I think we must not introduce changes to that function, as it may be used by many applications and it was not updated for the past versions. I think it's better to introduce a new function for that e.g. `ProxyHandlerRemote` , please do it and don't forget to use `gofmt` :P

**Review by kataras — CHANGES_REQUESTED** [review]
Hello @tuhao1020, how are you?

I think we must not introduce changes to that function, as it may be used by many applications and it was not updated for the past versions. I think it's better to introduce a new function for that e.g. `ProxyHandlerRemote` , please do it and don't forget to use `gofmt` :P

**Comment by tuhao1020** [comment]
@kataras   I have added ProxyHandlerRemote and NewProxyRemote, and code has formatted :)

**Review by kataras — APPROVED** [review]
LGTM, thanks @tuhao1020 (although there is a place for improvements there, e.g. remove the code duplication on the ProxyHandlerRemote, the 95% of the code is the same as the existing ones, but I will fix it later on)

**Comment by tuhao1020** [comment]
https://github.com/kataras/iris/blob/6c823e4864245481d12e97ac60eb1ab3ec9c1db4/core/host/proxy.go#L40-L55

Line 43: req.Host = target.Host
this line will make below code useless
https://github.com/kataras/iris/blob/6c823e4864245481d12e97ac60eb1ab3ec9c1db4/core/host/proxy.go#L70-L72
`req.Host = target.Host` should be placed after above code.

**Comment by kataras** [comment]
Oh you are totally right, merging the 2nd one now @tuhao1020 .

**Pull request merged**
