### PR TITLE
Add option DisplayFullBanner to display one-line banner

### PR DESCRIPTION
**Pull request by JulienBreux**
### Summary

**- Introduction**

A big thanks to @kataras for this amazing tool! 🍻 

**- What I did**

I add a new option `DisplayFullBanner` to display a small banner (one line).
It's very useful because we do an economy of ~7 lines in logs.

**- How I did it**

I've add the option `DisplayFullBanner` (default `true`).

**- How to verify it**

Create a small project with this option set to `false`:
```go
package main

import (
    "github.com/kataras/iris"
)

func main() {
        iris.Get("/iris-is-awesome", func(ctx *iris.Context){})
	iris.Config.DisplayFullBanner = false
	iris.Listen("8080")
}
```

And you should see:

`Sat, 28 Jan 2017 15:11:00 GMT: Iris x.x.x - Running at 0.0.0.0:8000`

#### Description

Add `DisplayFullBanner` option to display one-line banner at startup Iris.

#### Questions

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests?        | no

### CODE REVIEW

**Comment by lk-geimfari** [comment]
@JulienBreux The author does not accept contributions. Just [look at list](https://github.com/kataras/iris/graphs/contributors) of "contributors". If you wanna add feature then fork this project.

**Comment by JulienBreux** [comment]
@kataras are you alive?

**Comment by xor-gate** [comment]
Its a one mans island work, don't expect to get any usefull response.

**Comment by kataras** [comment]
@JulienBreux If you code like you post it would be perfect, but I can't accept this s.. I'm really sorry. It's not my fault that you don't read docs before posting a new PR.

This PR does not provide any new feature, neither fixes a bug. You were already done this before. 

Anyway even if I wanted to make you a 'surprise' and accept this thing, it has conflicts:/ 

Try harder next time please.

**Pull request closed without merging**
