### PR TITLE
Make a new logo for iris project

### PR DESCRIPTION
**Pull request by konhondros**
Every successful project, needs a well-done recognisable logo which represent the concept of project, based to the current iris logo recreated in a shape consistent from geometric elements with mathematic relations which can easy reproduced.
A square with rounded top-left and bottom-right corners by 50%,
Α concentric circle with diameter,  square's side / φ
Another one concentric circle with diameter, previous circle diameter / φ

### CODE REVIEW

**Comment by JulienBreux** [comment]
👍

**Comment by mamiu** [comment]
👍

**Comment by kataras** [comment]
Hello @konhondros, thanks for your time!!!



I just want you to inform about the flow of logos and how we choose to display one on README and iris-go.com, because it's a complicated (a creator has his/her own creation's rights).

**logo flow**  

People are pushing their logos there: https://github.com/iris-contrib/logo in order to have them in one place and anybody can know who did a logo for Iris and who 'won' the debate.

- Push a PR with a folder named as your github username, put the logo and some more sizes too if you can to https://github.com/iris-contrib/logo
- Every ~three months we select one via `Debate` github post issue.  
- Last step: I put the winning logo on README with the creator's link and name.

**Comment by kataras** [comment]
Hello @konhondros, thanks for your time!!!



I just want you to inform about the flow of logos and how we choose to display one on README and iris-go.com, because it's a complicated (a creator has his/her own creation's rights).

**logo flow**  

People are pushing their logos there: https://github.com/iris-contrib/logo in order to have them in one place and anybody can know who did a logo for Iris and who 'won' the debate.

- Push a PR with a folder named as your github username, put the logo and some more sizes too if you can to https://github.com/iris-contrib/logo
- Every ~three months we select one via `Debate` github post issue.  
- Last step: I put the winning logo on README with the creator's link and name.

A good `Debate` post with image decision is that: https://github.com/kataras/iris/issues/67 

I'm waiting your PR!!! Thanks again it looks great!

**Comment by corn13read** [comment]
@konhondros Thank you for contributing. I'm sorry your contribution will never be mentioned by the sad project owner. He can't even bring himself to merge a logo PR. Talk about a sad person.

**Pull request closed without merging**
