### PR TITLE
Native golang client implementing subset of server interface

### PR DESCRIPTION
**Pull request by jadeblaquiere**
This client implements the Emit(), EmitMessage(), On() and OnMessage(), OnDisconnect() and Disconnect() functions of the websocket.Connection interface and uses the iris.Config format for specifying connection configuration options. The dialer interface wraps gorilla.Dialer. Usage is illustrated in the test code. 

(btw, very open to suggestions on how to make this fit in nicely)

### CODE REVIEW

**Comment by jadeblaquiere** [comment]
Closing until I resolve test case reliability issues

**Comment by jadeblaquiere** [comment]
counters in test case implemented using sync/atomic and WaitGroup used to validate completion of concurrent writes

**Comment by kataras** [comment]
@jadeblaquiere  Seems a very decent and useful PR, finally.

Are you in position that you can answer and help users future issues regarding to your PR?
If yes, could you please add an example on [_examples/intermediate/websockets](https://github.com/kataras/iris/tree/master/_examples/intermediate/websockets) with a folder name like "websocket-client" too?  (we have one named custom-go-client which you can change it or remove at all, it's up to you what you think is better).

**Comment by jadeblaquiere** [comment]
Sure, I can help users with this component. I'll work on a simple, straightforward example and add it to the PR. 

Any thoughts on naming? Is ClientConnection intuitive?

**Comment by jadeblaquiere** [comment]
Let me know if there is anything you'd like me to change to align to the Iris style... otherwise I think this is ready to merge.

**Comment by kataras** [comment]
@jadeblaquiere It seems nice and I didn't expect you to [open an issue first](http://support.iris-go.com) because this is a feature request by many users already. I'm also glad that you made an easy how-to-use example for newcomers as I asked to.

As you may or may not know by pushing a PR to a big repository like this, which is used by small and bigger companies you're surrendered by your own use-copyrights (microsoft, mozilla, apache and other communities uses this term as well because to have copyrights from many unknown sources, like an open-source project makes difficult to manage and re-claim them if needed), please revert the changes from the license header of .go files if you're still want to merge them, other option for you is to make a new repository with your own copyrights which I will share too. Your name still be visible to the repository and the community or other party who may want to hire you. The pr can't be rebased because of some conflicts but I can fix them, don't worry for them!

**Comment by kataras** [comment]
@jadeblaquiere Is that your active github account? If yes could you please join to the [chat](https://kataras.rocket.chat/channel/iris) ? It will be nice to be here in order to answer some  future users questions about your PR.

**Comment by kataras** [comment]
@jadeblaquiere Is that your active github account? If yes could you please join to the [chat](https://kataras.rocket.chat/channel/iris) ? It will be nice(it's our responsibility) to be there in order to answer users' questions about your PR.

**Comment by jadeblaquiere** [comment]
Yes, I am joined to the chat.

**Comment by kataras** [comment]
@jadeblaquiere Please follow [this issue](https://github.com/kataras/iris/issues/658) and PR that to the winning repository or clone your self one and post it there!

**Comment by hiveminded** [comment]
@jadeblaquiere please update iris and transfer update the PR, I read its code it looks good to me.

**Pull request closed without merging**
