### PR TITLE
Fix all outstanding issues

### PR DESCRIPTION
**Pull request by icholy**
You're welcome!

### CODE REVIEW

**Comment by viru** [comment]
When can we expect it to be merged?

**Comment by slomek** [comment]
I need that for my project ASAP!

**Comment by BirknerAlex** [comment]
LGTM

**Comment by zet4** [comment]
LGTM

**Comment by MeltedLux** [comment]
LGTM

**Comment by kataras** [comment]
You want to remove the code of the repo? And what other communities who want to clone that and continue its development? You and the comments below are not respecting the community itself. Try spend your time on better things, not here please.

**Pull request closed without merging**
