### PR TITLE
support hash storage

### LINKED ISSUE #1610: [FEATURE REQUEST](session)UpdateExpiration on more than three million keys with radix lib
Hello Makis!

In a production environment, the redis cluster has more than three million keys. When the program operates the session (update the session expiration time), the redis cluster cpu soars to 50%, which takes several seconds.

While debugging I found place where freezes, it`s here:
```
func (r *RadixDriver) UpdateTTLMany(prefix string, newSecondsLifeTime int64) error {
	keys, err := r.getKeys("0", prefix)
	if err != nil {
		return err
	}
	...
}

func (r *RadixDriver) getKeys(cursor, prefix string) ([]string, error) {
	var res scanResult
	err := r.pool.Do(radix.Cmd(&res, "SCAN", cursor, "MATCH", r.Config.Prefix+prefix+"*", "COUNT", "300000"))
	if err != nil {
		return nil, err
	}
	...
}
// SCAN 72057594037927936 MATCH ucweb:10b7fd46-4275-46bb-b041-78d0bd1cfd30* COUNT 300000

```

Session storage mechanism, a user login state will have multiple string keys. As the number of users increases, redis key will gradually become very large. I extended a new version, the session storage in redis was changed to hash, and it also supports redis stand-alone mode and cluster mode. Hope to provide convenience for the vast number of development compatriots.

### PR DESCRIPTION
**Pull request by 1819997197**
Fixes #1610 

There are two solutions: 
1. Put it in the sessiondb/redis directory, at the same level as radix and redigo, advantages: code can be reused, disadvantages: more modifications, increasing the complexity of the code.

2. adding a database interface Implementation, shortcomings: partial code duplication; advantages: clear code structure. I chose the first option.

I need your help: I would like to integrate it perfectly into the sessiondb/redis directory.

### CODE REVIEW

**Comment by kataras** [comment]
Hello @1819997197, good one but why you copy-pasted the existing code (such as database and driver) to other directory? In your post comment you wrote that you selected the first option, so I assumed that the code will be injected inside the existing [sessiondb/redis/driver_radix.go](https://github.com/kataras/iris/blob/master/sessions/sessiondb/redis/driver_radix.go). At any case, you don't need to copy-paste the [sessiondb/redis/database.go](https://github.com/kataras/iris/blob/master/sessions/sessiondb/redis/database.go) file, it's the database object which is the frontier for all redis [drivers](https://github.com/kataras/iris/blob/8dc4fbdbbf10cbe48cfde71b98dd861b0372419b/sessions/sessiondb/redis/driver.go#L24-L34), both `radix` and `redigo`. You can add a `driver_radix_hash.go` and a new `RadixHashed` variable in the `driver.go` if you want a total new driver (second option in your post comment).

**Comment by 1819997197** [comment]
Hello @kataras.
Sorry, the second option was selected above. I will try to modify it again with the first scheme.

**Comment by kataras** [comment]
No worries @1819997197 , take your time. The release is posponded for two weeks more

**Comment by 1819997197** [comment]
hello @kataras.
I revised it according to the first scheme again, you have time to review it for me.

**Comment by kataras** [comment]
Hello @1819997197, why you added soo many changes and changed the logging logic and the database functions? There is no need for all that, you just have to use HKEYS instead of KEYS. Or they are required? please explain me as I have to maintain your code for the coming years...

**Comment by 1819997197** [comment]
Hello @kataras.
First of all, the implementation class of Driver interface needs to modify the redis operation at the bottom level, and this layer must be changed. Secondly, the implementation class of Database interface, string-keys and hash-keys operations are different, such as: Set, Get, Delete, Visit and other methods, so I abstracted a layer of DatabaseDriver interface.
If you have a better way, I am more willing to modify it. My intention is to integrate this function more perfectly into iris.

**Comment by kataras** [comment]
@1819997197 I don't see huge differences on how the key is created (using makeKey) or how the connection is open or how the configuration is passed on or what the `Set/Get/Clear` input arguments accept or why you changed the `Get` to `GetByKey` or how the `TTL` is stored. The only difference is that on SET/GET redis keys you are using their hashed version,e .g. `HGET` instead of `GET`.

Maybe you want to **fech from `master`** before pushing a PR? I see that you are using old code (v12.1.8). We can't merge that into v12.1.8 because it's a tagged release, so we have to push it on master, which is the upcoming version but you made that driver using v12.1.8 code instead :/

Let me help you: the only thing to make the driver work from normal keys to hashed keys is the `HSET` and `HGET` ( If that's the case, let me do the work so you can see we can go from 600 new lines to not even 30) or you did something else I am not able to see yet?

**Comment by kataras** [comment]
@1819997197 I don't see huge differences on how the key is created (using makeKey) or how the connection is open or how the configuration is passed on or what the `Set/Get/Clear` input arguments accept or why you changed the `Get` to `GetByKey` or how the `TTL` is stored. The only difference is that on SET/GET redis keys you are using their hashed version,e .g. `HGET` instead of `GET`.

Maybe you want to **fech from `master`** before pushing a PR? I see that you are using old code (v12.1.8). We can't merge that into v12.1.8 because it's a tagged release, so we have to push it on master, which is the upcoming version but you made that driver using v12.1.8 code instead :/

Let me help here:

1.The only thing to make the driver work from normal keys to hashed keys is the `HSET` and `HGET` ( If that's the case, let me do the work so you can see we can go from 600 new lines to not even 30) or you did something else I am not able to see yet? 
2. Did you run your code against the existing redis example?
3. Can you share with us the benchmark code you used to compare both redis db sessions implementations? 

Thank you a lot for your effort!

**Comment by 1819997197** [comment]
hello @kataras.
We have been running in the production environment for a week, and it is relatively stable at present(more than three million keys).

**Comment by kataras** [comment]
Yes but I asked you if the only necessary change is the "HKEYS" instead of "KEYS". I can't accept a PR like that, it copies paste things in different files without reason...

**Comment by kataras** [comment]
Yes but I asked you if the only necessary change is the "HKEYS" instead of "KEYS". I can't accept a PR like that, it copies paste things in different files without reason...you must fix it and also accept the license/cla. I will try to fix it in a different PR, so you can see ok?

**Comment by kataras** [comment]
Yes but I asked you if the only necessary change is the "HMSET/HMKEYS" instead of "SET(EX)/KEYS" and e.t.c? 

Also, can you explain us why is the "field" required, and why the `GetByKey` and `GetAll` return nil? How users should use the new API? And why you pushed from v12.1.8 instead of master ? There are too many questions...we have to discuss it my friend, so we can provide no breaking changes and also fix the issue, and also in order for me to be able to maintain these changes for the upcoming decade.

**Comment by 1819997197** [comment]
At present, I use v12.1.8 in the production environment. After finding the problem, I directly extend the database interface based on the current warehouse. My own way of using it is different from the two methods of raising pr. I understand what you mean. It's OK to solve this problem based on the master branch, but it takes a little time.

**Comment by kataras** [comment]
@1819997197 this is fixed, by using a totally different go redis driver, which performs a bit faster too. Please check out the following commit: https://github.com/kataras/iris/commit/cc7e3860f2e41c98b8ad7edd575cca45f6effe98. Thanks for opening this issue, please try it whenever you have time, note that you can still use your own implementation (if you change some method names) and you will be fine too

**Pull request closed without merging**
