### PR TITLE
websocket rebuild 1m

### PR DESCRIPTION
**Pull request by jjhesk**
we will open a new repo and branch to support these dirty works. The previous work are still defective and we need to rework it.
#1178, #1173

### CODE REVIEW

**Comment by jjhesk** [comment]
changed base

**Comment by kataras** [comment]
I don't see any new code/changes here. The new changes I coded yesterday for the "websocket rebuild 1m" is on the #1175 PR on the v11.2.0 [branch](https://github.com/kataras/iris/tree/v11.2.0), you can fetch from there, the package is `kataras/iris/websocket2` and the example which is using this temp new package is on the [_examples/websocket/go-client-stress-test](https://github.com/kataras/iris/tree/v11.2.0/_examples/websocket/go-client-stress-test). Push to the v11.2.0 instead, which is the work-in-progress branch for the next upcoming version (you can do a fork and push there, open a PR which targets the v11.2.0 branch and it will be fine)

**Comment by jjhesk** [comment]
yes. do you see ws1m?

**Comment by jjhesk** [comment]
its the complete same code and additional some wip.. im on the phone now..

**Comment by kataras** [comment]
Why not 10million? http://goroutines.com/10m

**Comment by kataras** [comment]
@jjhesk, I am working on the #1175 for the next v11.2 as I already told you... I did some work for the past weeks on the websockets to solve the  `C10M Problem`, not just handle 1million, we can already do that if the operating system and host's resources are allowing it. 

I see here two new packages, one is a copy from other repository and other is using a package that it is  only compatible with linux and this will break our ecosystem, be patient, soon I'll make public one of my private projects that I am working on - which end-user could be able to manage concurrency by himself-  it is based on the gobwas/ws package for lower-level websocket server and client usage, it will not be included into Iris.  Therefore scheduling and synchronization can be adapted manually and optionally by the end-developer as it should. Iris must keep work everywhere without limitation, I hope you understand.

**Comment by kataras** [comment]
Hello @jjhesk, 

Nice job and really thank you for your bug reports but I am working on the #1175 for the next v11.2 as I already told you... I did some work for the past weeks on the websockets to solve the  `C10M Problem`, not just handle 1million, we can already do that if the operating system and host's resources are allowing it. 

I see here two new packages, one is a copy from other repository and other is using a package that it is  only compatible with linux and this will break our ecosystem, be patient, soon I'll make public one of my private projects that I am working on - which end-user could be able to manage concurrency by himself-  it is based on the gobwas/ws package for lower-level websocket server and client usage, it will not be included into Iris.  Therefore scheduling and synchronization can be adapted manually and optionally by the end-developer as it should. Iris must everywhere without limitation, I hope you understand.

However, If you still want to do something and you can trust yourself on this, just create a new repository with a LINUX-only note - that will wrap iris' websocket (or make your own implementation, you know better) so Iris users can use it with the same API they used and loved to.


Thanks,
Gerasimos Maropoulos

**Comment by kataras** [comment]
Hello @jjhesk, 

Nice job and really thank you for your bug reports but I am working on the #1175 for the next v11.2 as I already told you... I did some work for the past weeks on the websockets to solve the  `C10M Problem`, not just handle 1million, we can already handle 1million if the operating system and host's resources are allowing it. 

I know that this is a WIP but I want to mention some things to help you proceed. 

I see here two new packages, one is a copy from other repository(?) and other is using a package that it is  only compatible with linux(!) and this will break our ecosystem.

I will give you some more days to work on this but we are almost ready for the release, I posponded it two times already. Keep note that I am also working on an external websocket low-level package that it is based on gobwas/ws, as you suggested on your issues, which end-user could be able to manage concurrency by himself, there is no need to be inside Iris itself. Therefore scheduling and synchronization can be adapted manually and optionally by the end-developer as it should.
Iris must run everywhere without limitation, I hope you understand.

However, If you still want to do something about your traffic issue and you can trust yourself on this, just create a new repository with a LINUX-only note - that will wrap iris' websocket (or make your own implementation, you know better) so Iris users can use it with the same API they used and loved to.


Thanks,
Gerasimos Maropoulos

**Comment by jjhesk** [comment]
@kataras your idea is clear and helpful. I total agree with you. You are the best =)

**Comment by jjhesk** [comment]
ws1m WIP and updates
Text

**Comment by jjhesk** [comment]
confirmed

**Comment by kataras** [comment]
Because I already push a new websocket module on the 11.2 PR and I don't see any changes here, is this a branch only to sync with the master? can you please point me what fixes/changes/new features you pushed and what is confirmed? Thanks @jjhesk

**Comment by jjhesk** [comment]
hi. @kataras there is nothing new in changes. the current socket is working fine. i am using it and tested on few projects. now we need to also make some example for protopuf testings on its versions

**Comment by kataras** [comment]
# Update

Read more at: https://github.com/kataras/neffos and https://dev.to/kataras/iris-version-11-2-released-22bc

**Pull request closed without merging**
