### PR TITLE
Update go.mod

### PR DESCRIPTION
**Pull request by mlboy**

### CODE REVIEW

**Comment by kataras** [comment]
Can you tell us the advandages of that update? I didn't test the new minor version of blackfriday myself, that dependency is used by other libraries as well, so I don't want any surprises.

**Comment by nordic-coder** [comment]
**Quick fix:**
go mod edit -replace=gopkg.in/russross/blackfriday.v2@v2.0.0=github.com/russross/blackfriday/v2@v2.0.0
**see:**
[https://github.com/russross/blackfriday/issues/491](url)

**Comment by kataras** [comment]
Oh thanks, could you please complete the checks above ^ so I can continue by approving it? Although it would be better to just open an issue first.

**Comment by mlboy** [comment]
go mod edit -replace=gopkg.in/russross/blackfriday.v2@v2.0.1=github.com/russross/blackfriday/v2@v2.0.1

**Pull request merged**
