### PR TITLE
Fix gofmt issues

### PR DESCRIPTION
**Pull request by artemnikitin**

### CODE REVIEW

**Comment by kataras** [comment]
Man thanks you for the pull request but I changed the graceful wait 10-15 minutes for the big commit you will see, many things will change from 3.0.0-alpha.1 to alpha.2 **thanks for the pull request, anyway!!**

**Comment by kataras** [comment]
If you do that on v2.3.2 I will approve but it's on master branch which I can't because it is useless after the changes I made *

**Comment by artemnikitin** [comment]
Ok, I will close this one then.

**Comment by kataras** [comment]
Wait for the next commit, do not create tests yet ( I'm updating the e-book now) after this I will commit the new version

**Comment by kataras** [comment]
@artemnikitin  Just finished finally... now you can start tests when you have time !

**Pull request closed without merging**
