### PR TITLE
Add comments for special ListeningAddr cases

### PR DESCRIPTION
**Pull request by positiveviking**
Can not pass emty address to iris.Listen #307

### CODE REVIEW

**Comment by kataras** [comment]
You know that I can't approve it, if you read the contribution file... anyway I did something different, set the default to '0.0.0.0' as it's by golang's default listener, and if someone has problems with their hosting machines they can just open an issue

**Comment by kataras** [comment]
You know that I can't approve it, if you read the contribution file.... anyway thanks for the try, keep like that!

I did something different, set the default to '0.0.0.0' as it's by golang's default listener, and if someone has problems with their hosting machines they can just open an issue

**Comment by positiveviking** [comment]
Thanks a lot.
I thought our discussion was near to deadlock and make this pr as an example of mimal efforts for fixing.
I promise to read contribution file before pull request with real code :)

Thank you for grate work on this framework. It really helps me to make my applications betterl.

**Comment by kataras** [comment]
No, we can always discuss for these things, no deadlocks here, nothing will be accoblished without community's feature requests and suggestions!

**Pull request closed without merging**
