### PR TITLE
Update Jet dep to 5.0.2

### PR DESCRIPTION
**Pull request by Dexus**
Update to last jet dep.

### CODE REVIEW

**Comment by kataras** [comment]
@Dexus did you test it with the current examples, does that version contain any breaking changes that we must know in order to change our Jet view engine?

**Comment by Dexus** [comment]
> > https://github.com/CloudyKit/jet/blob/master/docs/changes.md#v5
> 
> When updating from version 4 to version 5, there is a breaking changes:
> 
> _ became a reserved symbol
> 
> Version 5 uses _ for two new features: it adds Go-like discard syntax in assignments (assigning anything to _ will make jet skip the assignment) and to denote the argument slot for the piped value. When assigning to _, Jet will still always evaluate the corresponding right-hand side of the assignment statement, i.e. you can use _ to call a function but throw away its return value.
> 
> When you assign (and/or use) a variable called _ in your code, you will have to rename this variable.

**Comment by kataras** [comment]
But why you pushed a PR with a single go.mod file before opening an issue as the PR template says and before even testing the examples at least? :/ Why should I have to merge it when I will be the one who will check if the upgrade works or needs modification to the view engines?

**Comment by kataras** [comment]
...This PR broke the code now because you imported `github.com/CloudyKit/jet/v5` in `go.mod` file but not in the `view/jet.go` **import** declaration... you see why I was asking for testing the examples before pushing something like that? :P @Dexus it's fine I will fix it.

**Comment by kataras** [comment]
...This PR broke the code now because you imported `github.com/CloudyKit/jet/v5` in `go.mod` file but not in the `view/jet.go` **import** declaration (it still uses the `/v4` and now it cant find it)... you see why I was asking for testing the examples before pushing something like that? :P @Dexus it's fine I will fix it.

**Comment by Dexus** [comment]
Damn, sorry did forgot to push the commit with that changes.

Von meinem iPhone gesendet

**Comment by kataras** [comment]
No worries @Dexus and sorry for my tone is just I expect more from you, you understand. I feel you, sometimes we `git add .` make changes and push without new `git add .` command

**Pull request merged**
