### PR TITLE
UnmarshalBody UnmarshalBody with ioutil.ReadAll,maybe very dangerous

### PR DESCRIPTION
**Pull request by cocotyty**
I think maybe should use limit size reader,so  copy some codes from net/http ParseForm

### CODE REVIEW

**Comment by kataras** [comment]
I think this is server's job and not individual reader's functions, for example the `FormValue`  and general all post and get body functions should be have this body limit, or not? On iris v5 we had this limit on `iris.Config.MaxRequestBodySize`.

**Comment by cocotyty** [comment]
thank you for your reply.
We need a safe framework , this is  a security vulnerability.
FormValue is already have body limit,
see [https://godoc.org/net/http#Request.ParseForm](https://godoc.org/net/http#Request.ParseForm)
maybe i can write some codes to complete function about iris.Config.MaxRequestBodySize ,^_^

**Comment by kataras** [comment]
You seem a good dev but you didnt' read the CONTRIBUTION file...

**Comment by kataras** [comment]
I know about ParseForm I just gave an example in order to explain what I meant.

The last commit will have (small) affect on routing performance... please read the CONTRIBUTION files on the projects you want to contribute on

**Comment by kataras** [comment]
We have two solutions now, first: accept this solution on Readers and Unmarshalers only. The second (and my preffered) is to make a middleware and check if iris.Config.MaxRequestBodySize > 0 then and only then we add this middleware to all routes, parties and (sub)domains via `iris.UseGlobal` . This way we don't lose performance and we can easly turn it off/on when needed.

The user may want to add his/her logic on max request body size, for example she/he SHOULD BE FREE to change that value based on the `context.Request` and so on.. there are many situations, this is why I removed the MaxRequestBodySize with the default value of 32MB after v6... we need to discuss it

**Comment by kataras** [comment]
I made a little research and I saw that I made the right decision to remove the MaxRequestBodySize from v6 and let users decide for it , as one of the golang authors commented : https://github.com/golang/go/issues/2093#issuecomment-66057813 
```
Cap on header size is now in.  It defaults to 1MB but can be set per-Server:
http://code.google.com/p/go/source/detail?r=d499fb951a9e9ea0c370d15a7b1ccdfabfe71ba8
I don't see the need for LimitRequestBody, though.  That's per-Handler to decide.
Keeping this bug open, though, as there's still more to be done.
```

So I'll just make a helper function inside `Context` to help newcomers to solve that and also a handler to work as opional middleware

**Comment by kataras** [comment]
I made a little research and I saw that I made the right decision by removing the MaxRequestBodySize from v6 and not approve this PR (it was good idea but next time please discuss first) and let users decide for it , as one of the golang authors commented : https://github.com/golang/go/issues/2093#issuecomment-66057813 
```
Cap on header size is now in.  It defaults to 1MB but can be set per-Server:
http://code.google.com/p/go/source/detail?r=d499fb951a9e9ea0c370d15a7b1ccdfabfe71ba8
I don't see the need for LimitRequestBody, though.  That's per-Handler to decide.
Keeping this bug open, though, as there's still more to be done.
```

So I'll just make a helper function inside `Context` to help newcomers to solve that and also a handler to work as opional middleware

**Comment by kataras** [comment]
I think most users already know how to do this but for newcomers this new 'feature' will help a lot: https://github.com/kataras/iris/commit/d5a9410e2ae51adb0150828536d4ea8ff1a02730

**Pull request closed without merging**
