### PR TITLE
updating examples

### PR DESCRIPTION
**Pull request by sger**

### CODE REVIEW

**Comment by kataras** [comment]
Did you try to update with 'go get -u github.com/kataras/iris' ? I change from interface{} to string because 90% of reddit users/developers told me it's more clear for other users to pass just string in the listen

**Comment by sger** [comment]
yes i have the latest reason still the server is not working

**Comment by sger** [comment]
running ./named_parameters
maybe adding a default port (8080) and run it with
iris.Run()

**Comment by kataras** [comment]
No no I just tested it it worked with iris.Listen("8080") and iris.Listen(":8080") and api := iris.New() api.Listen(":8080") , please check again ( .Run is for other web framework :P) 

Also check, iris is first at the github trends for go https://github.com/trending/go

**Comment by sger** [comment]
my mistake it works with iris.Listen("8080") do you want to update the example as well?
Congrats nice work!

**Comment by sger** [comment]
i'm going to try iris with heroku maybe an example?

**Comment by kataras** [comment]
I think the example is ok I did fix the first example but you merged it with correct string, just add to ignore  executable files ( for example ./_examples/named_parameters)

**Comment by kataras** [comment]
To be honesty I see over 10h+ tutorials and examples how heroku works but because  I have my own server from the university I never try heroku myself. If you do this example it will help me too  :P

**Pull request merged**
