### PR TITLE
fixing example named_parameters

### PR DESCRIPTION
**Pull request by sger**

### CODE REVIEW

**Comment by kataras** [comment]
You know what, I think it's a bug, are you using linux ? at windows :8080 is working, if you use linux post that issue as bug - issue

**Comment by sger** [comment]
i'm on OS X.

**Comment by kataras** [comment]
Yes this is a bug on osx and propably linux too then, so we merge this until I fix it.

News 2, now we are on global trending projects, the only one Go project today which is at this list https://github.com/trending welldone !!!

**Comment by sger** [comment]
nice @kataras congrats!

**Pull request merged**
