### PR TITLE
add missing argument in readme for ctx.JSON

### PR DESCRIPTION
**Pull request by dpastoor**
ctx.JSON requires status

### CODE REVIEW

**Comment by kataras** [comment]
Hello @dpastoor ,

Sadly, you didn't read the contribution for PRs,
 
For core: PR which just editing a .MD file is not approved, if you find something strange and can be fixed in less than ~5 minutes, you should [ask](https://kataras.rocket.chat/channel/iris) from author to do it instead.

For gitbook: PR which contains typo fix or missing code changes are accepted and approved.

For examples: PR which add one more new example are accepted and approved.

For middleware: PR which adds a new middleware is accepted and approved.


However **I'm thanking you for your interest** and your good eye!
I will edit the README at the next revision, next time please contact with me first for these type of things.

Cheers,
kataras

**Comment by kataras** [comment]
Hello @dpastoor ,

I can't approve this, because first: 

Putted a '200' as integer, it would be better if: `iris.StatusOK` 

```go
  iris.Get("/myjson", func(ctx *iris.Context){
    ctx.JSON(iris.StatusOK, iris.Map{
      "Name": "Iris",
      "Released": "13 March 2016",
      "Stars": 5250,
    })
  })

```
and second:

sadly, you didn't read the contribution for PRs,
 
For core: PR which just editing a .MD file is not approved, if you find something strange and can be fixed in less than ~5 minutes, you should [ask](https://kataras.rocket.chat/channel/iris) from author to do it instead.

For gitbook: PR which contains typo fix or missing code changes are accepted and approved.

For examples: PR which add one more new example are accepted and approved.

For middleware: PR which adds a new middleware is accepted and approved.


However **I'm thanking you for your interest** and your good eye!
I will edit the README at the next revision, next time please contact with me first for these type of things.

Cheers,
kataras

**Comment by dpastoor** [comment]
not a problem! , and yes I actually did try chat, but it seems to be down

image

image

thus I figured a pull request would be easier to mention the change!

**Comment by kataras** [comment]
That's very strange, thanks for trying, I don't know why rocketchat had issues in your pc, but it seems that is working
img1

**Pull request closed without merging**
