### PR TITLE
add redis cluster driver

### LINKED ISSUE #1545: Session is stored in redis. Currently, redis cluster mode is not supported by using radix driver [BUG]
problem: Session is stored in redis. Currently, redis cluster mode is not supported by using radix driver.

Use example:
       cluster := []string{
		"redis://ip1:port1?password=pwd",
		"redis://ip1:port2?password=pwd",
		"redis://ip1:port3?password=pwd",
		"redis://ip2:port4?password=pwd",
		"redis://ip2:port5?password=pwd",
		"redis://ip2:port6?password=pwd",
		"redis://ip3:port7?password=pwd",
		"redis://ip3:port8?password=pwd",
		"redis://ip3:port9?password=pwd",
	}
	db := redis.New(redis.Config{
		Network:   "tcp",
		Addr:      "", 
		Timeout:   time.Duration(30) * time.Second,
		MaxActive: 10,
		Password:  "",
		Driver:     redis.Radix() 
		Clusters:  cluster,
	})

       iris.RegisterOnInterrupt(func() {
		db.Close()
	})

	defer db.Close()

	sess := sessions.New(sessions.Config{
		Cookie:       "sessionscookieid",
		AllowReclaim: true,
	})
       app := iris.New()
	app.Get("/set/int/{key}/{value}", func(ctx iris.Context) {
		key := ctx.Params().Get("key")
		value, _ := ctx.Params().GetInt("value")
		s := sess.Start(ctx)
		// set session values
		s.Set(key, value)
		valueSet := s.Get(key)
		// test if set here
		ctx.Writef("All ok session value of the '%s' is: %v", key, valueSet)
	})

	app.Get("/get/{key}", func(ctx iris.Context) {
		key := ctx.Params().Get("key")
		value := sess.Start(ctx).Get(key)

		ctx.Writef("The '%s' on the /set was: %v", key, value)
	})
       app.Run(iris.Addr(":50050"), iris.WithoutServerError(iris.ErrServerClosed))

error info:
panic: should never get here

### PR DESCRIPTION
**Pull request by 1819997197**
Fixes #1545

### CODE REVIEW

**Comment by 1819997197** [comment]
@kataras Before, radix driver did not support redis cluster. #1545

**Comment by kataras** [comment]
Yes @1819997197 it didn't work because the documented code of mediocregopher/radix/v3 for clustering is not working, it needs a separate `Cluster` field, and you found it but you don't need to add a new driver for that, we already support it, we just need to use `radix.Cluster` instead of `radix.Pool` when Clusters configuration field > 0. Read my commit in a few minutes and you will see.

**Comment by kataras** [comment]
Also your code does not respect the `Timeout` field, for some reason you force-set a second dial timeout option to 1 minute.

**Comment by kataras** [comment]
OK @1819997197, the real fix was just 6 new code lines. Not 223 as your PR added. That was your first PR and it's acceptable to do those mistakes, especially if you are not too familiar with the Go language. With Iris you will learn a lot, by pushing PRs, finding bugs and fill issues, reading its source code and e.t.c.

**Comment by 1819997197** [comment]
@1819997197 OK, great

**Comment by kataras** [comment]
Yeah, you can read the changes required at: https://github.com/kataras/iris/commit/01a17081b853ae2e2a57ae8d026b5c9010a29886. You welcome @1819997197 I thank you for finding the bug and filling an issue and a PR, please test it once more and we are ready to move on to the next great thing:)

**Comment by 1819997197** [comment]
@kataras OK, Thx

**Comment by kataras** [comment]
You are welcome @1819997197 !!

**Pull request merged**
