### PR TITLE
update sessions.RemoveCookie

### PR DESCRIPTION
**Pull request by WingGao**
We should use `ctx.RemoveCookie` to remove the cookie in the request at same time.

### CODE REVIEW

**Comment by kataras** [comment]
No, we keep the `context#RemoveCookie` and sessions separated by decision , not my accident but thank you for your try:P  (the Iris' session is the fastest and most featured library in the Go world, we must make it easy to other people to just use that but don't want to use Iris :))

**Comment by WingGao** [comment]
In this case
```
// we want to destroy the old session
_session.Destroy(ctx)
// and get a new session
sessNew := _session.Star(ctx)
```
After that, the response will lost the new session, because the new session use the old key.

**Comment by kataras** [comment]
So you want to use another session in the same request for the same user and current implementation doesn't let you because it removes the cookie from `Response` and not from the `Request` at the same time ( which is for safety reasons), we must add an option for this in the configuration, can you do that instead? (If not no problem I will do it right now)

**Comment by kataras** [comment]
Done:
```go
sess = sessions.New(sessions.Config{Cookie: "cookiename", AllowReclaim: true})
```

If `AllowReclaim` is true (is false by-default) then it removes the cookie from the temporary request's store as well, as you asked, although I wouldn't recomend this because it may cause you a headache if you use many handlers to serve a single request and accidentally re-claim the session, because it will use the new session store instead of the old and the values will be cleared. But it's there now if you need it.

Thank you very much @WingGao , keep up like this!

**Comment by WingGao** [comment]
Great! Thank you!

**Pull request closed without merging**
